- name: Make sure that set_passwords are setup properly
  set_fact:
    local_set_passwords: "{{ set_passwords | default(false) }}"
    jenkins_casc_dirname: "jenkins_casc_standard"

- name: Apply templating onto the jenkins CasC file
  template: 
    src: "{{ templates_dir }}/{{ jenkins_casc_dirname }}/jenkins.yaml.j2"
    dest: "{{ repository_dir }}/jenkins_casc/jenkins.yaml"
  vars:
    set_passwords: "{{ local_set_passwords }}" 
