# Goal: Start up Jenkins until it finishes its setup and then stop it.
- name: "Start Jenkins App"
  become: yes
  shell: docker compose up --build -d

- name: Wait for Jenkins App to fully start up
  shell: ./check_jenkins_read.py http://127.0.0.1:8080/jenkins/

- name: "Stop Jenkins App"
  become: yes
  shell: docker compose down
