# Goal: Start up Jenkins until it finishes its setup and then stop it.
- name: "Start Jenkins App"
  become: yes
  shell: docker compose up --build -d
  args:
    chdir: "{{ playbook_dir }}/../../" 

- name: Wait for Jenkins App to fully start up
  shell: python3 ./check_jenkins_ready.py http://127.0.0.1:8080/jenkins/
  args:
    chdir: "{{ playbook_dir }}/../../"

- name: "Stop Jenkins App"
  become: yes
  shell: docker compose down
  args:
    chdir: "{{ playbook_dir}}/../../"
